# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qoe8_XWMt0HCPRLxmDeKs5w1HOroROZW
"""

!pip install pytesseract
!sudo apt install tesseract-ocr
!pip install Pillow pytesseract

from PIL import Image
import matplotlib.pyplot as plt

# Upload the image to Colab first, then use its path
image_path = 'image_ocr.png'  # Replace with the path to your image

# Load and display the image
img = Image.open(image_path)
plt.imshow(img)
plt.axis('off')  # Turn off axis numbers and ticks
plt.show()

gray = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)

_, thresh = cv2.threshold(gray, 150, 255, cv2.THRESH_BINARY_INV)

# Deskew, denoise, or other preprocessing steps here...


text = pytesseract.image_to_string(thresh)

print(text)